export * from './clazzDto';
export * from './fileDto';
export * from './fileGenerationDataDto';
export * from './okStatus';
export * from './roomDto';
export * from './sampleDto';
export * from './seatDto';
export * from './studentDto';
export * from './studentPc';
