@baseUrl = https://localhost:7226


################################################## classes
GET {{baseUrl}}/classes
#####

################################################## Pdf
GET {{baseUrl}}/Pdf/DownloadTestFile
#####
GET {{baseUrl}}/Pdf/ReadFile?fileName=abc&fullPath=abc
#####
POST {{baseUrl}}/Pdf/Create
Content-type: application/json

{
   "clazzName": "abc",
   "roomName": "abc",
   "imageBase64": "abc",
   "studentPcList":
   [{
      "studentName": "abc",
      "pcNr": 1
   }]
}
#####

################################################## rooms
GET {{baseUrl}}/rooms
#####

################################################## Sample
GET {{baseUrl}}/Sample/AuthorizeTest
#####
GET {{baseUrl}}/Sample/Test
#####

################################################## seats
GET {{baseUrl}}/seats?roomName=abc
#####

################################################## students
GET {{baseUrl}}/students
#####

################################################## Values
GET {{baseUrl}}/Values/Persons
#####
